oi:
  variations:
    - 'moin'
    - 'oi'
    - 'niom'
    - 'noim'
    - 'mion'

irc:
  channels:
    - '#channelOne'
    - '#channelTwo'
  server: 'irc.example.org'
  port: 6697
  tls: true
  username: 'oi'
  passphrase: 'forNickServ'
