moin:
  variations:
    - 'moin'
    - 'oi'
    - 'niom'
    - 'noim'
    - 'mion'
  allowedUsers:
    - 'moinbot'
    - 'oibot'
    - 'noimbot'
    - 'MOINbot'
    - 'OIbot'
    - 'moibot'

irc:
  channels:
    - '#channelOne'
    - '#channelTwo'
  server: 'irc.example.org'
  port: 6697
  tls: true
  username: 'moin'
  passphrase: 'forNickServ'
