services:
  moin:
    image: moin
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/lib/moin:/usr/src/app/data
      - ./config.yml:/usr/src/app/config.yml:ro
